### ISSUE TITLE
为量表增加UID

### ISSUE THREAD

**Issue by yangguang-ecnu** [MR-algorithms/PsiScale#11]
UID用于唯一地标识量表。由于在目前的情况下，量表的编号比较容易改变，所以使用量表编号作为答卷与量表之间的联系，出现问题的可能性比较大。
应该为量表自动分配UID，并且在量表发生版本变化时，自动修改量表的UID，确保答卷与量表之间的对应关系不会错误地改变。

**Comment by LiDongbao** [comment]
UID已经实现。
