### ISSUE TITLE
如果一开始在输入问题的时候没有选择子量表，则问题没有子量表属性。

### ISSUE THREAD

**Issue by WenJingLi** [MR-algorithms/PsiScale#30]
假设输入第一题的时候没有选择子量表，之后又没有重新回到第一题进行选择，则第一题没有子量表属性。

**Comment by yangguang-ecnu** [comment]
已解决。如果第一题没有选择子量表，则编辑后面题目后返回第一题时，ComboBox中显示为空，使得用户能够知道这一题尚未选择子量表。
谢谢WenJingLi！
