### ISSUE TITLE
结果查询和显示需求：实验数据--使用UID查询和显示被试的测试结果；被试信息--显示全部被试信息。

### ISSUE THREAD

**Issue by LiDongbao** [MR-algorithms/PsiScale#60]
实验的数据，可以根据被试UId查询答题结果（多次答题的、多个Scale的结果）；Data ：被试编号，出生年月，民族，体重，填表日期，填表结束时间点（区分同一量表前后两次填写顺序），题目答案/得分，子量表（Group）得分，总分；
被试的信息显示，需要直接显示全部被试信息。Message：被试编号，姓名，姓名拼音，出生年月，性别，民族，体重，手机，电邮，填表年龄（可后期处理）。

**Comment by salan668** [comment]
在Pull Request #71 中解决.
